from tkinter import *
window = Tk()
window.title("Converter")
window.configure(background="light blue")
from businesslogic import *

def from_kg():
    gram = kg2g(e2_value.get())
    gram  = round(gram ,2)
    pounds = kg2p(e2_value.get())
    pounds = round(pounds,2)
    ounce = kg2o(e2_value.get())
    ounce = round(ounce,2)
    t1.delete("1.0", END)
    t1.insert(END, gram)
    t2.delete("1.0", END)
    t2.insert(END, pounds)
    t3.delete("1.0", END)
    t3.insert(END, ounce)

def from_m():
    cm = m2cm(e3_value.get())
    cm  = round(cm ,2)
    feet = m2f(e3_value.get())
    feet  = round(feet ,2)
    inch = m2i(e3_value.get())
    inch  = round(inch ,2)
    t4.delete("1.0",END)
    t4.insert(END, cm)
    t5.delete("1.0", END)
    t5.insert(END, feet)
    t6.delete("1.0", END)
    t6.insert(END, inch)

def from_celsius():
    farenheit = c2f(e4_value.get())
    farenheit  = round(farenheit ,2)
    kelvin = c2k(e4_value.get())
    kelvin  = round(kelvin ,2)
    t7.delete("1.0",END)
    t7.insert(END, farenheit)
    t8.delete("1.0", END)
    t8.insert(END,  kelvin)


e1 = Label(window, text = "Enter the value to be converted from kg", fg="black", bg="green")
e2_value = StringVar()
e2 = Entry(window, textvariable=e2_value)
e3 = Label(window, text="gram", fg="black", bg="blue")
e4 = Label(window, text="pounds", fg="black", bg="blue")
e5 = Label(window,text="ounce", fg="black", bg="blue")
t1 = Text(window, height=1,width =20)
t2 = Text(window,height=1,width=20)
t3 = Text(window,height=1,width=20)
b1 = Button(window, text="Convert",command=from_kg, fg="black", bg="red")

e6 = Label(window, text = "Enter the value to be converted from meter", fg="black", bg="green")
e3_value = StringVar()
e7 = Entry(window, textvariable=e3_value)
e8 = Label(window,text="cm", fg="black", bg="blue")
e9 = Label(window,text="feet", fg="black", bg="blue")
e10 = Label(window,text="inch", fg="black", bg="blue")
t4 = Text(window, height=1,width =20)
t5 = Text(window,height=1,width=20)
t6 = Text(window,height=1,width=20)
b2 = Button(window, text="Convert",command=from_m, fg="black", bg="red")

e11 = Label(window, text = "Enter the value to be converted from celsius", fg="black", bg="green")
e4_value = StringVar()
e12 = Entry(window, textvariable=e4_value)
e13 = Label(window,text="farenheit", fg="black", bg="blue")
e14 = Label(window,text="kelvin", fg="black", bg="blue")
#e15 = Label(window,text="inch", fg="black", bg="blue")
t7 = Text(window, height=1,width =20)
t8 = Text(window,height=1,width=20)
#t9 = Text(window,height=1,width=20)
b3 = Button(window, text="Convert",command=from_celsius, fg="black", bg="red")

e1.grid(row=0,column=0)
e2.grid(row=0,column=1)
e3.grid(row=1,column=0)
e4.grid(row=1,column=1)
e5.grid(row=1,column=2)
t1.grid(row=2,column=0)
t2.grid(row=2,column=1)
t3.grid(row=2,column=2)
b1.grid(row=0,column=2)

e6.grid(row=4,column=0)
e7.grid(row=4,column=1)
e8.grid(row=5,column=0)
e9.grid(row=5,column=1)
e10.grid(row=5,column=2)
t4.grid(row=6,column=0)
t5.grid(row=6,column=1)
t6.grid(row=6,column=2)
b2.grid(row=4,column=2)

e11.grid(row=8,column=0)
e12.grid(row=8,column=1)
e13.grid(row=9,column=0)
e14.grid(row=9,column=1)
#e15.grid(row=9,column=2)
t7.grid(row=10,column=0)
t8.grid(row=10,column=1)
#t9.grid(row=10,column=2)
b3.grid(row=8,column=2)

window.mainloop()